version: '3.8'

services:
  backend:
    build:
      context: .
    container_name: centralised-backend-container
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=centralised_backend_db
      - DB_USER=centralised_user
      - DB_PASSWORD=123
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres-db-container
    environment:
      POSTGRES_DB: centralised_backend_db
      POSTGRES_USER: centralised_user
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
