services:
  backend:
    build:
      context: ./centralised-backend
    ports:
      - "8000:8000"
    env_file:
      - ./centralised-backend/.env
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: centralised_backend_db
      POSTGRES_USER: centralised_user_user
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./centralised-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
