# Generated by Django 5.1.4 on 2025-03-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_email_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hostel_number',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='roll_number',
            field=models.CharField(default='000000', max_length=50, unique=True),
        ),
    ]
