name: CI/CD Pipeline

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      working-directory: Centralised-SARC/centralised-frontend
      run: npm install --legacy-peer-deps

    - name: Fix Permissions Issue
      working-directory: Centralised-SARC/centralised-frontend
      run: sudo chmod -R 777 ./node_modules/.bin

    - name: Build frontend
      working-directory: Centralised-SARC/centralised-frontend
      run: npm run build

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install backend dependencies
      working-directory: Centralised-SARC/centralised-backend
      run: |
        python -m venv env
        source env/bin/activate
        pip install -r requirements.txt

    - name: Run Backend Tests
      working-directory: Centralised-SARC/centralised-backend
      run: |
        source env/bin/activate
        python manage.py test

    - name: Build and Deploy with Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install docker.io docker-compose -y
        docker-compose -f Centralised-SARC/docker-compose.yml up --build -d
